# Generated by Django 4.1.3 on 2022-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=60)),
                ('user', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('host', models.CharField(max_length=60)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
